version: "3.0"
services:
    bancodados:
        image: "mysql:latest"
        environment: 
            MYSQL_ROOT_PASSWORD: "M#str@d0"
            MYSQL_DATABASE: "moodledb"
            MYSQL_USER: "moodleuser"
            MYSQL_PASSWORD: "M#str@d0"
        ports:
            - "3307:3306"
        networks:
            platao-net:
        volumes:
            - /var/lib/mysql

    moodleapp:
        build: .
        ports: 
            - "80:80"
            - "443:443"
        networks: 
            - platao-net
        volumes:
            - /var/www/moodle
            - /usr/moodledata

networks:
    platao-net:

volumes: 
    moodle-vol:
    moodledata-vol:
    dbvolume:

